/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DataSourcesRouteImport } from './routes/data-sources'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as TariffsRouteImport } from './routes/tariffs'
import { Route as AnalyzeIdRouteImport } from './routes/analyze.$id'
import { Route as AnalyzeIdActRouteImport } from './routes/analyze.$id.act'
import { Route as AnalyzeIdCapitalRouteImport } from './routes/analyze.$id.capital'
import { Route as AnalyzeIdFinanceRouteImport } from './routes/analyze.$id.finance'
import { Route as AnalyzeIdFitRouteImport } from './routes/analyze.$id.fit'
import { Route as AnalyzeIdFundingRouteImport } from './routes/analyze.$id.funding'
import { Route as AnalyzeIdMarketRouteImport } from './routes/analyze.$id.market'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DataSourcesRoute = DataSourcesRouteImport.update({
  id: '/data-sources',
  path: '/data-sources',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const TariffsRoute = TariffsRouteImport.update({
  id: '/tariffs',
  path: '/tariffs',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzeIdRoute = AnalyzeIdRouteImport.update({
  id: '/analyze/$id',
  path: '/analyze/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzeIdActRoute = AnalyzeIdActRouteImport.update({
  id: '/act',
  path: '/act',
  getParentRoute: () => AnalyzeIdRoute,
} as any)
const AnalyzeIdCapitalRoute = AnalyzeIdCapitalRouteImport.update({
  id: '/capital',
  path: '/capital',
  getParentRoute: () => AnalyzeIdRoute,
} as any)
const AnalyzeIdFinanceRoute = AnalyzeIdFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AnalyzeIdRoute,
} as any)
const AnalyzeIdFitRoute = AnalyzeIdFitRouteImport.update({
  id: '/fit',
  path: '/fit',
  getParentRoute: () => AnalyzeIdRoute,
} as any)
const AnalyzeIdFundingRoute = AnalyzeIdFundingRouteImport.update({
  id: '/funding',
  path: '/funding',
  getParentRoute: () => AnalyzeIdRoute,
} as any)
const AnalyzeIdMarketRoute = AnalyzeIdMarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => AnalyzeIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/data-sources': typeof DataSourcesRoute
  '/onboarding': typeof OnboardingRoute
  '/tariffs': typeof TariffsRoute
  '/analyze/$id': typeof AnalyzeIdRouteWithChildren
  '/analyze/$id/act': typeof AnalyzeIdActRoute
  '/analyze/$id/capital': typeof AnalyzeIdCapitalRoute
  '/analyze/$id/finance': typeof AnalyzeIdFinanceRoute
  '/analyze/$id/fit': typeof AnalyzeIdFitRoute
  '/analyze/$id/funding': typeof AnalyzeIdFundingRoute
  '/analyze/$id/market': typeof AnalyzeIdMarketRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/data-sources': typeof DataSourcesRoute
  '/onboarding': typeof OnboardingRoute
  '/tariffs': typeof TariffsRoute
  '/analyze/$id': typeof AnalyzeIdRouteWithChildren
  '/analyze/$id/act': typeof AnalyzeIdActRoute
  '/analyze/$id/capital': typeof AnalyzeIdCapitalRoute
  '/analyze/$id/finance': typeof AnalyzeIdFinanceRoute
  '/analyze/$id/fit': typeof AnalyzeIdFitRoute
  '/analyze/$id/funding': typeof AnalyzeIdFundingRoute
  '/analyze/$id/market': typeof AnalyzeIdMarketRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/data-sources': typeof DataSourcesRoute
  '/onboarding': typeof OnboardingRoute
  '/tariffs': typeof TariffsRoute
  '/analyze/$id': typeof AnalyzeIdRouteWithChildren
  '/analyze/$id/act': typeof AnalyzeIdActRoute
  '/analyze/$id/capital': typeof AnalyzeIdCapitalRoute
  '/analyze/$id/finance': typeof AnalyzeIdFinanceRoute
  '/analyze/$id/fit': typeof AnalyzeIdFitRoute
  '/analyze/$id/funding': typeof AnalyzeIdFundingRoute
  '/analyze/$id/market': typeof AnalyzeIdMarketRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/data-sources'
    | '/onboarding'
    | '/tariffs'
    | '/analyze/$id'
    | '/analyze/$id/act'
    | '/analyze/$id/capital'
    | '/analyze/$id/finance'
    | '/analyze/$id/fit'
    | '/analyze/$id/funding'
    | '/analyze/$id/market'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/data-sources'
    | '/onboarding'
    | '/tariffs'
    | '/analyze/$id'
    | '/analyze/$id/act'
    | '/analyze/$id/capital'
    | '/analyze/$id/finance'
    | '/analyze/$id/fit'
    | '/analyze/$id/funding'
    | '/analyze/$id/market'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/data-sources'
    | '/onboarding'
    | '/tariffs'
    | '/analyze/$id'
    | '/analyze/$id/act'
    | '/analyze/$id/capital'
    | '/analyze/$id/finance'
    | '/analyze/$id/fit'
    | '/analyze/$id/funding'
    | '/analyze/$id/market'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  DataSourcesRoute: typeof DataSourcesRoute
  OnboardingRoute: typeof OnboardingRoute
  TariffsRoute: typeof TariffsRoute
  AnalyzeIdRoute: typeof AnalyzeIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-sources': {
      id: '/data-sources'
      path: '/data-sources'
      fullPath: '/data-sources'
      preLoaderRoute: typeof DataSourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tariffs': {
      id: '/tariffs'
      path: '/tariffs'
      fullPath: '/tariffs'
      preLoaderRoute: typeof TariffsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyze/$id': {
      id: '/analyze/$id'
      path: '/analyze/$id'
      fullPath: '/analyze/$id'
      preLoaderRoute: typeof AnalyzeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyze/$id/act': {
      id: '/analyze/$id/act'
      path: '/act'
      fullPath: '/analyze/$id/act'
      preLoaderRoute: typeof AnalyzeIdActRouteImport
      parentRoute: typeof AnalyzeIdRoute
    }
    '/analyze/$id/capital': {
      id: '/analyze/$id/capital'
      path: '/capital'
      fullPath: '/analyze/$id/capital'
      preLoaderRoute: typeof AnalyzeIdCapitalRouteImport
      parentRoute: typeof AnalyzeIdRoute
    }
    '/analyze/$id/finance': {
      id: '/analyze/$id/finance'
      path: '/finance'
      fullPath: '/analyze/$id/finance'
      preLoaderRoute: typeof AnalyzeIdFinanceRouteImport
      parentRoute: typeof AnalyzeIdRoute
    }
    '/analyze/$id/fit': {
      id: '/analyze/$id/fit'
      path: '/fit'
      fullPath: '/analyze/$id/fit'
      preLoaderRoute: typeof AnalyzeIdFitRouteImport
      parentRoute: typeof AnalyzeIdRoute
    }
    '/analyze/$id/funding': {
      id: '/analyze/$id/funding'
      path: '/funding'
      fullPath: '/analyze/$id/funding'
      preLoaderRoute: typeof AnalyzeIdFundingRouteImport
      parentRoute: typeof AnalyzeIdRoute
    }
    '/analyze/$id/market': {
      id: '/analyze/$id/market'
      path: '/market'
      fullPath: '/analyze/$id/market'
      preLoaderRoute: typeof AnalyzeIdMarketRouteImport
      parentRoute: typeof AnalyzeIdRoute
    }
  }
}

interface AnalyzeIdRouteChildren {
  AnalyzeIdActRoute: typeof AnalyzeIdActRoute
  AnalyzeIdCapitalRoute: typeof AnalyzeIdCapitalRoute
  AnalyzeIdFinanceRoute: typeof AnalyzeIdFinanceRoute
  AnalyzeIdFitRoute: typeof AnalyzeIdFitRoute
  AnalyzeIdFundingRoute: typeof AnalyzeIdFundingRoute
  AnalyzeIdMarketRoute: typeof AnalyzeIdMarketRoute
}

const AnalyzeIdRouteChildren: AnalyzeIdRouteChildren = {
  AnalyzeIdActRoute: AnalyzeIdActRoute,
  AnalyzeIdCapitalRoute: AnalyzeIdCapitalRoute,
  AnalyzeIdFinanceRoute: AnalyzeIdFinanceRoute,
  AnalyzeIdFitRoute: AnalyzeIdFitRoute,
  AnalyzeIdFundingRoute: AnalyzeIdFundingRoute,
  AnalyzeIdMarketRoute: AnalyzeIdMarketRoute,
}

const AnalyzeIdRouteWithChildren = AnalyzeIdRoute._addFileChildren(
  AnalyzeIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  DataSourcesRoute: DataSourcesRoute,
  OnboardingRoute: OnboardingRoute,
  TariffsRoute: TariffsRoute,
  AnalyzeIdRoute: AnalyzeIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
